Repository VictorAvelar/laravel-dashboard-football-data-advanced, pull requests merged in 2022-10, with the labels that each got.

#1 feat(standings): add command to fetch and store league standings
  src/Commands/FetchLeagueStandingsCommand.php
  src/Stores/LeagueStandingsStore.php
Labels: hacktoberfest

#5 feature(upcoming): add command to fetch and store upcoming matches:
  src/Commands/FetchUpcomingFootballMatchesCommand.php
  src/Config.php
  src/Stores/UpcomingFootballMatchesStore.php
Labels: hacktoberfest, hacktoberfest-accepted

#6 Feature/laravel config and setup
  src/Commands/FetchLeagueStandingsCommand.php
  src/Commands/FetchMatchResultsCommand.php
  src/FetchDataFromApiCommand.php
  src/FootballDataAdvancedTilesServiceProvider.php
  src/MyStore.php
  src/MyTileComponent.php
  src/MyTileServiceProvider.php
  src/Stores/MatchResultsStore.php
Labels: hacktoberfest, hacktoberfest-accepted

#7 Feature/frontend components and livewire setup
  resources/views/results.blade.php
  resources/views/standings.blade.php
  resources/views/tile.blade.php
  resources/views/upcoming.blade.php
  src/Components/LeagueStandingsTileComponent.php
  src/Components/MatchResultsTileComponent.php
  src/Components/UpcomingMatchesTileComponent.php
  src/FootballDataAdvancedTilesServiceProvider.php
Labels: hacktoberfest, hacktoberfest-accepted

#13 Refactored data values passed to view in LeagueStandingsTileComponent…
  src/Components/LeagueStandingsTileComponent.php
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#12 Fixed typo in ServiceProvider. Issue #9
  src/ServiceProvider.php
Labels: bug, hacktoberfest, hacktoberfest-accepted

#15 fix(upcoming) display values for priority matches
  resources/views/upcoming.blade.php
  src/ServiceProvider.php
Labels: hacktoberfest, hacktoberfest-accepted
